<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="PoleSensor">

  <xacro:property name="PI" value="3.14159" />
  <xacro:property name="mass1" value="10" />
  <xacro:property name="mass2" value="1" />
  <xacro:property name="width1" value="0.1" />
  <xacro:property name="width2" value="0.1" />
  <xacro:property name="length1" value="1.5" />
  <xacro:property name="length2" value="0.1" />
  <xacro:property name="Custom_length" value="0.275935" />
  <!-- <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" /> -->

  <xacro:include filename="$(find panda_description)/urdf/sensor_stick.gazebo.xacro" />


  <link name="world" />

  <link name="link_1">
    <visual>
      <geometry><box size="${width1} ${width1} ${length1}" /></geometry>
      <material name="blue"><color rgba="0.0 0.0 0.8 1.0" /></material>
    </visual>
    <collision>
      <geometry><box size="${width1} ${width1} ${length1}" /></geometry>
    </collision>
    <inertial>
      <mass value="${mass1}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <link name="link_2">
    <visual>
      <geometry><box size="${width2} ${width2} ${length2}" /></geometry>
      <material name="white"><color rgba="1.0 1.0 1.0 1.0" /></material>
    </visual>
    <collision>
      <geometry><box size="${width2} ${width2} ${length2}" /></geometry>
    </collision>
    <inertial>
      <mass value="${mass2}" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

   <link name='camera_link'>
    <pose>0 0 0 0 0 0</pose>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"
      />
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 0" rpy="0 0 0"/> 
      <geometry>
        <box size=".03 .03 .03"/>
      </geometry>
    </collision>

    <visual name='camera_link_visual'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".03 .03 .03"/>
      </geometry>
    </visual>

  </link>

  <joint name="fixed_base_joint" type="fixed">
    <parent link="world" />
    <child link="link_1" />
    <origin xyz="0 -2 -${Custom_length}" rpy="0 0 0" />
  </joint>

  <joint name="pan_joint" type="fixed">
    <parent link="link_1" />
    <child link="link_2" />
    <axis xyz="0 0 1" />
    <origin xyz="0 0 ${length1/2+length2/2}" rpy="0 0 ${PI/2}" />
  </joint>

  <joint name="tilt_joint" type="fixed">
    <origin xyz="0.05 0 ${length2/2+0.02}" rpy="0 0.5 0" />
    <parent link="link_2" />
    <child link="camera_link" />
    <axis xyz="0 1 0" />
  </joint>


 <!-- <xacro:sensor_d435 parent="camera_mount_link"
      use_nominal_extrinsics="true" add_plug="false"
      use_mesh="true">
      <origin xyz="0.8 0.0 0.05" rpy="0 0.0 0" />
    </xacro:sensor_d435> -->

 <joint type="fixed" name="camera_optical_joint">
    <origin xyz="0 0 0" rpy="-1.5707 0 -1.5707"/>
    <child link="camera_link_optical"/>
    <parent link="camera_link"/>
  </joint>

  <link name="camera_link_optical">
  </link>

</robot>
